version: '2.1'

services:
  mongodb:
    image: mongo:4.2.5
    container_name: mongo-java-server-test
    tmpfs:
      - /data:rw
    ports:
      - 127.0.0.1:27018:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet 1
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:9.6-alpine
    container_name: postgres-mongo-java-server-test
    tmpfs:
      - /var/lib/postgresql/data:rw
    environment:
      - POSTGRES_USER=mongo-java-server-test
      - POSTGRES_PASSWORD=mongo-java-server-test
      - POSTGRES_DB=mongo-java-server-test
    ports:
      - 127.0.0.1:5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  sonarqube:
    image: sonarqube
    container_name: mongo-java-server-sonarqube
    ports:
      - 127.0.0.1:9000:9000
